name: Workflow

on: push

jobs:
  # build:
  #   name: Build Locally
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4.1.1
  #   - name: Download Dependencies
  #     uses: awalsh128/cache-apt-pkgs-action@v1.3.0
  #     with:
  #       packages: cmake ninja-build libboost-all-dev libreadline-dev
  #       version: local
  #   - name: Cache Local Build
  #     uses: actions/cache@v3.3.2
  #     with:
  #       path: ${{ github.workspace }}/build
  #       key: local-build
  #   - name: Build
  #     run: ./build.sh ./ build/
  deploy:
    name: Build Container Image with Docker
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Download Dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1.3.0
      with:
        packages: docker
        version: docker
    - name: Log in to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0
    - name: Set up buildx
      uses: docker/setup-buildx-action@v3.0.0
      with:
        driver-opts: network=host
    - name: Build Runtime Image
      uses: docker/build-push-action@v5.0.0
      with:
        tags: localhost:5000/runtime
        file: ${{ github.workspace }}/images/runtime.Containerfile
        context: ${{ github.workspace }}
        push: true
        cache-from: type=registry,ref=fackop/ppshell:buildcache-runtime
        cache-to: type=registry,ref=fackop/ppshell:buildcache-runtime,mode=max
    - name: Build Test Image
      uses: docker/build-push-action@v5.0.0
      with:
        tags: test
        file: ${{ github.workspace }}/images/test.Containerfile
        context: ${{ github.workspace }}
        push: false
        load: true
        build-contexts: runtime=docker-image://localhost:5000/runtime
        cache-from: type=registry,ref=fackop/ppshell:buildcache-test
        cache-to: type=registry,ref=fackop/ppshell:buildcache-test,mode=max
    - name: Run Tests in Image
      run: docker run test --verbose --showlocals
    - name: Build and Deploy the Deploy Image
      uses: docker/build-push-action@v5.0.0
      with:
        tags: fackop/ppshell:latest
        file: ${{ github.workspace }}/images/deploy.Containerfile
        context: ${{ github.workspace }}
        push: ${{ github.ref_name == 'main' }}
        build-contexts: runtime=docker-image://localhost:5000/runtime
        cache-from: type=registry,ref=fackop/ppshell:buildcache-deploy
        cache-to: type=registry,ref=fackop/ppshell:buildcache-deploy,mode=max
  build-image-podman:
    name: Build Container Image with Podman
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Download Dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1.3.0
      with:
        packages: podman
        version: podman
    - name: Cache Buildah Restore
      id: cache-buildah-restore
      uses: actions/cache/restore@v3.3.2
      with:
        path: /tmp/containers
        key: buildah
    - name: Build Image
      run: podman --root /tmp/containers build --layers --tag runtime --file images/runtime.Containerfile ./
    - name: Delete Cache
      if: ${{ steps.cache-buildah-restore.outputs.cache-hit }}
      continue-on-error: true
      run: |
        gh extension install actions/gh-actions-cache
        gh actions-cache delete buildah --confirm
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Cache Buildah Save
      uses: actions/cache/save@v3.3.2
      with:
        path: /tmp/containers
        key: ${{ steps.cache-buildah-restore.outputs.cache-primary-key }}
